name: OCI Instance Provisioner Loop
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *' # Runs automatically every 15 minutes
  push:
    branches:
      - main

jobs:
  provision:
    runs-on: ubuntu-latest
    name: Run Capacity Provisioner Loop
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: curl, openssl, mbstring

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --optimize-autoloader

      - name: Create Private Key File
        run: |
          cat << 'EOF' > oci_private_key.pem
          ${{ secrets.OCI_PRIVATE_KEY || vars.OCI_PRIVATE_KEY }}
          EOF
          chmod 600 oci_private_key.pem

      - name: Generate Local .env File
        run: |
          cat << 'EOF' > .env
          OCI_REGION="sa-bogota-1"
          OCI_USER_ID="${{ secrets.OCI_USER_OCID || vars.OCI_USER_OCID }}"
          OCI_TENANCY_ID="ocid1.tenancy.oc1..aaaaaaaar2wm6lvli54b7tkzvu3vwnftuekuavabdgzhdfyd323slbuo7b7a"
          OCI_KEY_FINGERPRINT="${{ secrets.OCI_FINGERPRINT || vars.OCI_FINGERPRINT }}"
          OCI_PRIVATE_KEY_FILENAME="oci_private_key.pem"
          OCI_IMAGE_ID="ocid1.image.oc1.sa-bogota-1.aaaaaaaaamazzndcgdip6ca3nh5krclvupqn65x23wif6kr3hbm3zbcplc7q"
          OCI_OCPUS="2"
          OCI_MEMORY_IN_GBS="12"
          OCI_SHAPE="VM.Standard.A1.Flex"
          OCI_MAX_INSTANCES="1"
          OCI_SSH_PUBLIC_KEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDXzP+AKRFR5XosipOa+HjrPxX8MA+u0A1qb8nspvppek/BuCtFXoAYJ3fOZT54N2HyeWfkwu5YOB06wsiQvj26cyFYhFqYFX/PznOfl6WFA2W1m5xArw+gAvwEJdP/0+e3EoY73/1NI+P9zTZLWa9zQm5EP5dAZ8/WQVWRtuPAqwrY0JzsKxwNcdQzFfRV56+sB4rAnU8WBkdA1lLUARRNUNoGSYTwGrwiWG5js9/aaovb5ptXMVbvGovA2VfXvzVXKX0XJZ6whTJbYjxTBVJBNyMEO811MszndvbM9ymMIPjTqq1imLqM1Ce7oRl839zIEjQ8khyoXx47e1qTayx3NsiVC4pc2y5uSLdjVJJa8W2PLtug7Gzj431hIUC+VFrxAVJu1MgMZMQSz47jgmp7udoAiRH3N5erq9QE6F2qjZt1w+uAAP/ND/YjoMEsWrr4Zbh5OnTdZ13t3vMcqO9Hiz62IdmfDrFbQPEqpijj8jTDVMtJakSPU4pjoKLVOfH1gQFoobomTZ7eajAF6KG8XvvLbXyGr5jcVQoZkN0isOz/Tt2NCojj7kXKJe06siPgM+DXdwEDtmFCAPKoYjCLVlt41aoT/BMRpAOAZjItKcc+3KHhZ3q6VUAKWsXkQZ4bExaPk9DWPkKM6i8I+P5UPRIp47HeiDCmESMPACatWQ== pmaya@pmayaduque"
          TELEGRAM_USER_ID="${{ secrets.TELEGRAM_USER_ID || vars.TELEGRAM_USER_ID }}"
          TELEGRAM_BOT_API_KEY="${{ secrets.TELEGRAM_BOT_API_KEY || vars.TELEGRAM_BOT_API_KEY }}"
          OCI_AVAILABILITY_DOMAIN="ueCB:SA-BOGOTA-1-AD-1"
          OCI_SUBNET_ID="ocid1.subnet.oc1.sa-bogota-1.aaaaaaaay7aetpmqb2iao7j42kjzidbqf7og64kjnndiblnyqihdiciq6c4a"
          EOF

      - name: Execute Provisioner Script
        env:
          OCI_REGION: "sa-bogota-1"
          OCI_USER_ID: "${{ secrets.OCI_USER_OCID || vars.OCI_USER_OCID }}"
          OCI_TENANCY_ID: "ocid1.tenancy.oc1..aaaaaaaar2wm6lvli54b7tkzvu3vwnftuekuavabdgzhdfyd323slbuo7b7a"
          OCI_KEY_FINGERPRINT: "${{ secrets.OCI_FINGERPRINT || vars.OCI_FINGERPRINT }}"
          OCI_PRIVATE_KEY_FILENAME: "oci_private_key.pem"
          OCI_IMAGE_ID: "ocid1.image.oc1.sa-bogota-1.aaaaaaaaamazzndcgdip6ca3nh5krclvupqn65x23wif6kr3hbm3zbcplc7q"
          OCI_OCPUS: "2"
          OCI_MEMORY_IN_GBS: "12"
          OCI_SHAPE: "VM.Standard.A1.Flex"
          OCI_MAX_INSTANCES: "1"
          OCI_SSH_PUBLIC_KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDXzP+AKRFR5XosipOa+HjrPxX8MA+u0A1qb8nspvppek/BuCtFXoAYJ3fOZT54N2HyeWfkwu5YOB06wsiQvj26cyFYhFqYFX/PznOfl6WFA2W1m5xArw+gAvwEJdP/0+e3EoY73/1NI+P9zTZLWa9zQm5EP5dAZ8/WQVWRtuPAqwrY0JzsKxwNcdQzFfRV56+sB4rAnU8WBkdA1lLUARRNUNoGSYTwGrwiWG5js9/aaovb5ptXMVbvGovA2VfXvzVXKX0XJZ6whTJbYjxTBVJBNyMEO811MszndvbM9ymMIPjTqq1imLqM1Ce7oRl839zIEjQ8khyoXx47e1qTayx3NsiVC4pc2y5uSLdjVJJa8W2PLtug7Gzj431hIUC+VFrxAVJu1MgMZMQSz47jgmp7udoAiRH3N5erq9QE6F2qjZt1w+uAAP/ND/YjoMEsWrr4Zbh5OnTdZ13t3vMcqO9Hiz62IdmfDrFbQPEqpijj8jTDVMtJakSPU4pjoKLVOfH1gQFoobomTZ7eajAF6KG8XvvLbXyGr5jcVQoZkN0isOz/Tt2NCojj7kXKJe06siPgM+DXdwEDtmFCAPKoYjCLVlt41aoT/BMRpAOAZjItKcc+3KHhZ3q6VUAKWsXkQZ4bExaPk9DWPkKM6i8I+P5UPRIp47HeiDCmESMPACatWQ== pmaya@pmayaduque"
          TELEGRAM_USER_ID: "${{ secrets.TELEGRAM_USER_ID || vars.TELEGRAM_USER_ID }}"
          TELEGRAM_BOT_API_KEY: "${{ secrets.TELEGRAM_BOT_API_KEY || vars.TELEGRAM_BOT_API_KEY }}"
          OCI_AVAILABILITY_DOMAIN: "ueCB:SA-BOGOTA-1-AD-1"
          OCI_SUBNET_ID: "ocid1.subnet.oc1.sa-bogota-1.aaaaaaaay7aetpmqb2iao7j42kjzidbqf7og64kjnndiblnyqihdiciq6c4a"
        run: php index.php
